services:
  server:
    image: vladmarlo/hell_kitchen_gateway:latest
    ports:
      - 8000:8000
    environment:
      BIND_PORT: 8000
  tags:
    image: vladmarlo/tags_backend:latest
    environment:
      - POSTGRES_HOST=tags_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=tags
      - POSTGRES_PASSWORD=postgres
      - BIND_PORT=5000
    depends_on:
      tags_db:
        condition: service_healthy
      tags_migrate:
        condition: service_completed_successfully
  tags_migrate:
    image: vladmarlo/tags_migrator:latest
    restart: no
    environment:
      - POSTGRES_HOST=tags_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=tags
      - POSTGRES_PASSWORD=postgres
    depends_on:
      tags_db:
        condition: service_healthy
  tags_db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - tags-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tags
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 15
volumes:
  tags-db-data:


