services:
  api:
    image: vladmarlo/hell_kitchen_gateway:latest
    environment:
      - BIND_PORT=8000
      - TAGS_ADDR=grpc://tags:5000
      - USE_TLS=false
    restart: always
    depends_on:
      - tags
  tags:
    image: vladmarlo/tags_backend:latest
    environment:
      - POSTGRES_HOST=tags_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=tags
      - POSTGRES_PASSWORD=postgres
      - BIND_PORT=5000

    restart: always
    depends_on:
      tags_db:
        condition: service_healthy
      tags_migrate:
        condition: service_completed_successfully
  tags_migrate:
    image: vladmarlo/tags_migrator:latest
    restart: no
    environment:
      - POSTGRES_HOST=tags_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=tags
      - POSTGRES_PASSWORD=postgres
    depends_on:
      tags_db:
        condition: service_healthy
  tags_db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - tags-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tags
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 15
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart:
      always
    depends_on:
      - api
volumes:
  tags-db-data: