// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.22.0--rc2
// source: api/tags.proto

package tags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Slug  string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_api_tags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_api_tags_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type TagsGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TagsGetRequest) Reset() {
	*x = TagsGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsGetRequest) ProtoMessage() {}

func (x *TagsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsGetRequest.ProtoReflect.Descriptor instead.
func (*TagsGetRequest) Descriptor() ([]byte, []int) {
	return file_api_tags_proto_rawDescGZIP(), []int{1}
}

func (x *TagsGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TagsGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag *Tag `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *TagsGetResponse) Reset() {
	*x = TagsGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tags_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsGetResponse) ProtoMessage() {}

func (x *TagsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tags_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsGetResponse.ProtoReflect.Descriptor instead.
func (*TagsGetResponse) Descriptor() ([]byte, []int) {
	return file_api_tags_proto_rawDescGZIP(), []int{2}
}

func (x *TagsGetResponse) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type TagsGetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TagsGetAllRequest) Reset() {
	*x = TagsGetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tags_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsGetAllRequest) ProtoMessage() {}

func (x *TagsGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tags_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsGetAllRequest.ProtoReflect.Descriptor instead.
func (*TagsGetAllRequest) Descriptor() ([]byte, []int) {
	return file_api_tags_proto_rawDescGZIP(), []int{3}
}

type TagsGetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag []*Tag `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
}

func (x *TagsGetAllResponse) Reset() {
	*x = TagsGetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tags_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsGetAllResponse) ProtoMessage() {}

func (x *TagsGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tags_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsGetAllResponse.ProtoReflect.Descriptor instead.
func (*TagsGetAllResponse) Descriptor() ([]byte, []int) {
	return file_api_tags_proto_rawDescGZIP(), []int{4}
}

func (x *TagsGetAllResponse) GetTag() []*Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type TagsCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Slug  string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *TagsCreateRequest) Reset() {
	*x = TagsCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tags_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsCreateRequest) ProtoMessage() {}

func (x *TagsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tags_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsCreateRequest.ProtoReflect.Descriptor instead.
func (*TagsCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_tags_proto_rawDescGZIP(), []int{5}
}

func (x *TagsCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagsCreateRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TagsCreateRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type TagsCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Slug  string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *TagsCreateResponse) Reset() {
	*x = TagsCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tags_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsCreateResponse) ProtoMessage() {}

func (x *TagsCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tags_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsCreateResponse.ProtoReflect.Descriptor instead.
func (*TagsCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_tags_proto_rawDescGZIP(), []int{6}
}

func (x *TagsCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagsCreateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagsCreateResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TagsCreateResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_api_tags_proto protoreflect.FileDescriptor

var file_api_tags_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x53, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x20, 0x0a, 0x0e, 0x54,
	0x61, 0x67, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a,
	0x0f, 0x54, 0x61, 0x67, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x74, 0x61, 0x67, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x13, 0x0a,
	0x11, 0x54, 0x61, 0x67, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x31, 0x0a, 0x12, 0x54, 0x61, 0x67, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x54, 0x61, 0x67,
	0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x51, 0x0a, 0x11, 0x54, 0x61, 0x67, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x62, 0x0a, 0x12, 0x54, 0x61, 0x67, 0x73,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x32, 0xc1, 0x01, 0x0a,
	0x0b, 0x54, 0x61, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x54, 0x61,
	0x67, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x14, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e,
	0x54, 0x61, 0x67, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x74, 0x61,
	0x67, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x73,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x61, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_tags_proto_rawDescOnce sync.Once
	file_api_tags_proto_rawDescData = file_api_tags_proto_rawDesc
)

func file_api_tags_proto_rawDescGZIP() []byte {
	file_api_tags_proto_rawDescOnce.Do(func() {
		file_api_tags_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_tags_proto_rawDescData)
	})
	return file_api_tags_proto_rawDescData
}

var file_api_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_tags_proto_goTypes = []interface{}{
	(*Tag)(nil),                // 0: tags.Tag
	(*TagsGetRequest)(nil),     // 1: tags.TagsGetRequest
	(*TagsGetResponse)(nil),    // 2: tags.TagsGetResponse
	(*TagsGetAllRequest)(nil),  // 3: tags.TagsGetAllRequest
	(*TagsGetAllResponse)(nil), // 4: tags.TagsGetAllResponse
	(*TagsCreateRequest)(nil),  // 5: tags.TagsCreateRequest
	(*TagsCreateResponse)(nil), // 6: tags.TagsCreateResponse
}
var file_api_tags_proto_depIdxs = []int32{
	0, // 0: tags.TagsGetResponse.tag:type_name -> tags.Tag
	0, // 1: tags.TagsGetAllResponse.tag:type_name -> tags.Tag
	5, // 2: tags.TagsService.Create:input_type -> tags.TagsCreateRequest
	1, // 3: tags.TagsService.Get:input_type -> tags.TagsGetRequest
	3, // 4: tags.TagsService.GetAll:input_type -> tags.TagsGetAllRequest
	6, // 5: tags.TagsService.Create:output_type -> tags.TagsCreateResponse
	2, // 6: tags.TagsService.Get:output_type -> tags.TagsGetResponse
	4, // 7: tags.TagsService.GetAll:output_type -> tags.TagsGetAllResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_tags_proto_init() }
func file_api_tags_proto_init() {
	if File_api_tags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_tags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tags_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tags_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tags_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsGetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tags_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsGetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tags_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tags_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_tags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tags_proto_goTypes,
		DependencyIndexes: file_api_tags_proto_depIdxs,
		MessageInfos:      file_api_tags_proto_msgTypes,
	}.Build()
	File_api_tags_proto = out.File
	file_api_tags_proto_rawDesc = nil
	file_api_tags_proto_goTypes = nil
	file_api_tags_proto_depIdxs = nil
}
